import Head from 'next/head';

function Layout({ children }) {
	return (
		<>
			<Head>
				{/* Page Description */}
				<meta name='description' content='Generated by create next app' />
				{/* Favicon */}
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{/* Nav Content */}

			{/* Main Content */}
			<main>{children}</main>
		</>
	);
}

export default Layout;
