import Head from 'next/head';
import Header from '../components/header/header';
import Hero from '../components/hero/hero';
import Services from '../components/services/services';
import Articles from '../components/articles/articleSection';
import Testimonials from '../components/testimonials/testimonials';
import Projects from '../components/projects/projects';
import LowerCta from '../components/lowerCta/lowerCta';
import Footer from '../components/footer/footer';

export default function Home() {
	return (
		<>
			<Head>
				{/* Page Title */}
				<title>NV Marketing, LLC</title>
				{/* Page Description */}
				<meta name='description' content='Generated by create next app' />
			</Head>

			<Header />
			<main>
				<Hero />
				<Services />
				<Articles />
				<Testimonials />
				<Projects />
				<LowerCta />
			</main>
			<Footer />
		</>
	);
}
